services:
  web:
    build: ./web
    ports:
      - "8000:5000"
  monitoring:
    build: ./monitoring
    ports:
      - "8010:5010"
  redis:
    image: "redis:alpine"
  smtp:
    image: namshi/smtp
    ports:
     - "25:25"
    environment:
      - SMARTHOST_ADDRESS=${SMARTHOST_ADDRESS}
      - SMARTHOST_USER=${SMARTHOST_USER}
      - SMARTHOST_PASSWORD=${SMARTHOST_PASSWORD}
      - SMARTHOST_ALIASES=${SMARTHOST_ALIASES}