services:
  web:
    build: ./web
    ports:
      - "8000:5000"
  monitoring:
    build: ./monitoring
    ports:
      - "8010:5010"
  redis:
    image: "redis:alpine"
  smtp:
    image: namshi/smtp
    ports:
     - "25:25"
    environment:
      - SMARTHOST_ADDRESS=mail.mysmtp.com
      - SMARTHOST_USER=myuser
      - SMARTHOST_PASSWORD=secret
      - SMARTHOST_ALIASES=*.mysmtp.com